document.write("<h1 style='text-align:center; color:red'>External JavaScript</h1>" + "<br>")
document.write("<ol style='font-size:30px'>")
    document.write("<li>" + 100 + " Tejas " + "</li>")
    document.write("<li>" + 23.45 + true + "</li>")
document.write("</ol>")