// Math Method

// 1)   toDateString()
// 2)   getDate()
// 3)   getFullYear()
// 4)   getMonth()
// 5)   getDay()
// 6)   getHours()
// 7)   getMinutes()
// 8)   getSeconds()
// 9)   getMiliseconds()
// 10)  setDate()
// 11)  setFullYear()
// 12)  setHours()
// 13)  setMiliseconds()
// 14)  setMinutes()
// 15)  setMonths()
// 16)  setSeconds()